Praca_inżynierska_apka/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path

from django.conf.urls.static import static
from django.conf import settings
from users.forms import ValidateEmailForgotPassword

from users import views as user_views
from orders import views as order_views


urlpatterns = [
    path('admin/', admin.site.urls),

    path('rejestracja/', user_views.RegisterView.as_view(), name='users-register'),
    path('login/', user_views.MyLoginView.as_view(template_name='users/login.html'), name='users-login'),
    path('wyloguj/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='users-logout'),
    path('zresetuj-haslo/', auth_views.PasswordResetView.as_view(template_name='users/password_reset.html',
                                                                 form_class=ValidateEmailForgotPassword),
         name='password_reset'),
    path('zresetuj-haslo-potwierdz/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(
         template_name='users/password_reset_confirm.html'), name='password_reset_confirm'),
    path('zresetuj-haslo/gotowe', auth_views.PasswordResetDoneView.as_view(
         template_name='users/password_reset_done.html'), name='password_reset_done'),
    path('zresetuj-haslo/zakonczone', auth_views.PasswordResetCompleteView.as_view(
         template_name='users/password_reset_complete.html'), name='password_reset_complete'),

    path('adres/',user_views.ListOfAddressesView.as_view(), name='users-address_list'),
    path('adres/dodaj', user_views.CreateNewAddressView.as_view(), name='users-address_create'),
    path('adres/<int:pk>/zaktualizuj', user_views.UpdateAddressView.as_view(), name='users-address_update'),
    path('address/<int:pk>/delete', user_views.DeleteAddressView.as_view(), name='users-address_confirm_delete'),

    path('dodaj-do-koszyka/', order_views.add_to_cart, name='orders-add_to_cart'),
    path('koszyk/', order_views.manage_cart, name='orders-cart'),
    path('zamowienia/wybor-adresu-dostawy', user_views.SelectAddressView.as_view(), name='users-address_select'),
    path('zamowienia/<str:email>', user_views.UserOrdersListView.as_view(), name='orders-orders'),
    path('zamowienia/szczegoly-zamowienia/<int:pk>', user_views.ItemsInOrderListView.as_view(),
         name='orders-order_details'),

    path('statystyki', order_views.StatisticsView.as_view(), name='orders-statistics'),
    path('', include('restaurants.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.MEDIA_URL)

restaurants/urls.py
from django.urls import path
from .views import RestaurantListView, FoodRestaurantListView, FoodDetailView, IndexView, AboutView

urlpatterns = [
    path('', IndexView.as_view(), name='restaurants-index'),
    path('o-stronie/', AboutView.as_view(), name='restaurants-about'),
    path('restauracje/', RestaurantListView.as_view(), name='restaurants-list'),
    path('restauracje/<slug>/', FoodRestaurantListView.as_view(), name='restaurants-foods'),
    path('restauracje/<slug>/<int:category__id>', FoodRestaurantListView.as_view(), name='restaurants-foods-category'),
    path('restauracje/<slug:restaurant_slug>/<slug:food_slug>', FoodDetailView.as_view(), name='food-detail'),
]

restaurants/models.py
from django.core.files.base import ContentFile
from django.db import models
from django.utils.safestring import mark_safe
from users.models import UserDeliveryInformation

import segno
from io import BytesIO
from PIL import Image
from pyzbar.pyzbar import decode


class Restaurant(models.Model):
    name = models.CharField("Restauracja:",max_length=150)
    address = models.CharField("Adres:", max_length=255)
    city = models.CharField("Miasto:", max_length=150, default="Kraków")
    slug = models.SlugField("URL:",max_length=50)
    image = models.ImageField(upload_to='restaurant_logos', default='restaurant-default.png')

    class Meta:
        verbose_name = "Restauracja"
        verbose_name_plural = "Restauracje"

    def __str__(self):
        return '{} {} '.format(self.name, self.address)


class Category(models.Model):
    name = models.CharField("Kategoria:", max_length=150)
    slug = models.SlugField(max_length=50)

    class Meta:
        verbose_name = "Kategoria"
        verbose_name_plural = "Kategorie"

    def __str__(self):
        return self.name


class Food(models.Model):
    name = models.CharField("Nazwa dania", max_length=150)
    category = models.ManyToManyField(Category)
    slug = models.SlugField(max_length=50)
    price = models.DecimalField("Cena", max_digits=10, decimal_places=2)  # pole dla ceny
    restaurant = models.ForeignKey(Restaurant, on_delete=models.CASCADE, verbose_name="Restauracja")  # Klucz obcy do modelu restauracja
    description = models.TextField(blank=True, max_length=500)
    # kalorie i ig (cukier dla cukrzyków)
    calories = models.CharField(blank=True, max_length=50, verbose_name='Kalorie')
    ig = models.CharField(blank=True, max_length=50, verbose_name='Indeks glikemiczny')
    # kod qr dla informacji powyżej
    qr_code = models.ImageField(upload_to='food_qr_codes', blank=True)

    class Meta:
        verbose_name = "Posiłek"
        verbose_name_plural="Posiłki"

    def get_categories(self):
        return self.category.distinct()

    def read_qr_code(self):
        data = decode(Image.open(self.qr_code))
        return mark_safe(data[0].data.decode())

    def __str__(self):  # metoda do wyświetlania obiektu w django admin, dodajemy zł do pola ceny
        return '{} {}'.format(self.name, self. restaurant)

    def save(self, *args, **kwargs):
        buffer = BytesIO()
        qr_code_img = segno.make(f'Informacje dodatkowe:\n Kalorie: {self.calories}\n Indeks glikemiczny: {self.ig}')
        qr_code_img.save(buffer, kind='png', light='#FFFFFF', scale=4)
        self.qr_code.save(f'{self.name}-qrcode.png', ContentFile(buffer.getvalue()), save=False)
        super().save(*args, **kwargs)


class FoodImage(models.Model):
    food = models.ForeignKey(Food, on_delete=models.CASCADE, verbose_name="Posiłek")
    image = models.ImageField(upload_to="food_images", blank=True, verbose_name="Obraz")
    thumbnail = models.ImageField(upload_to="food-thumbnails", blank=True, null=True, verbose_name="Miniatura")

    class Meta:
        verbose_name ="Obraz produktu"
        verbose_name_plural = "Obrazy produktu"

    def image_tag(self):
        return mark_safe('<img src="/media/{}"/>'.format(self.image))

    image_tag.short_description = 'Obraz'

    def __str__(self):
        return self.food.name

restaurants/views.py
from django.http import Http404
from django.views.generic import DetailView, ListView, TemplateView
from django.utils.translation import gettext_lazy as _

from .models import Restaurant, Food, Category


class IndexView(TemplateView):
    template_name = 'restaurants/index.html'


class AboutView(TemplateView):
    template_name = 'restaurants/about.html'


class RestaurantListView(ListView):
    model = Restaurant
    template_name = 'restaurants/restaurant_list.html'
    context_object_name = 'restaurants'


class FoodRestaurantListView(ListView):
    model = Food
    template_name = 'restaurants/restaurant_foods.html'
    context_object_name = 'foods'

    def get_queryset(self):
        food = Food.objects.filter(restaurant__slug=self.kwargs.get('slug'))
        food_by_category = food.filter(category=self.kwargs.get('category__id'))
        if self.kwargs.get('category__id'):
            return food_by_category
        return food

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = Category.objects.filter(food__restaurant__slug=self.kwargs.get('slug')).distinct()

        return context


class FoodDetailView(DetailView):
    model = Food
    template_name = 'restaurants/food_detail.html'
    context_object_name = 'food_detail'

    def get_object(self, queryset=None):
        if queryset is None:
            queryset = self.get_queryset()
        restaurant_slug = self.kwargs.get('restaurant_slug', None)
        food_slug = self.kwargs.get('food_slug', None)
        try:
            obj = queryset.get(slug=food_slug, restaurant__slug=restaurant_slug)
        except queryset.model.DoesNotExist:
            raise Http404(_("Nie znaleziono takiego posiłku"))
        return obj

restaurants/templates/restaurants/about.html
{% extends 'restaurants/base.html' %}
{% block content %}
    <div class="content-section">
        <h1 class="text-center">
            Strona internetowa utworzona w celu opracowania tematu pracy inżynierskiej: <br> <br>
            <b>
                <i>
                    "Opracowanie i implementacja systemu online do zamawiania posiłków z obsługą czytnika kodów QR"
                </i>
            </b>
        </h1>
        <h3 class="text-right">
            <b>Autor:</b> <i>Tomasz Wańczyk</i>
        </h3>

        <h4 class="text-right">
            Wydział Inżynierii Metali i Informatyki Przemysłowej <br>
            Edukacja Techniczno-Informatyczna
        </h4>
    </div>
{% endblock %}

restaurants/templates/restaurants/base.html
{% load static %}
<!DOCTYPE html>
<html lang="pl">
<head>
     <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{% static 'restaurants/main.css' %}">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Lato&display=swap" rel="stylesheet">

    {% if title %}
        <title>Student zamawia - {{ title }}</title>
    {% else %}
        <title>Student zamawia</title>
    {% endif %}

</head>
<body>
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-light bg-steel fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="{% url 'restaurants-index' %}">
              <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-house-door-fill" fill="currentColor"
                   xmlns="http://www.w3.org/2000/svg">
                  <path d="M6.5 10.995V14.5a.5.5 0 0 1-.5.5H2a.5.5 0 0 1-.5-.5v-7a.5.5 0 0 1 .146-.354l6-6a.5.5 0 0 1
                  .708 0l6 6a.5.5 0 0 1 .146.354v7a.5.5 0 0 1-.5.5h-4a.5.5 0 0 1-.5-.5V11c0-.25-.25-.5-.5-.5H7c-.25
                  0-.5.25-.5.495z"/>
                  <path fill-rule="evenodd" d="M13 2.5V6l-2-2V2.5a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5z"/>
              </svg>
              <b>Student zamawia</b>
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href="{% url 'restaurants-about' %}">O stronie</a>
              <a class="nav-item nav-link" href="{% url 'orders-statistics' %}">Statystyki</a>
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
            {% if request.cart.count > 0 %}
                <a class="nav-item nav-link" style="color:#00693C" href="{% url 'orders-cart' %}">Koszyk
                    <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-cart" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                      <path fill-rule="evenodd" d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .491.592l-1.5 8A.5.5 0 0 1 13 12H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5zM3.102 4l1.313 7h8.17l1.313-7H3.102zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm-7 1a1 1 0 1 0 0 2 1 1 0 0 0 0-2zm7 0a1 1 0 1 0 0 2 1 1 0 0 0 0-2z"/>
                    </svg>
                  ({{ request.cart.count }})
                </a>
            {% else %}
                <a class="nav-item nav-link" href="{% url 'orders-cart' %}">Koszyk
                     <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-cart" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                      <path fill-rule="evenodd" d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .491.592l-1.5 8A.5.5 0 0 1 13 12H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5zM3.102 4l1.313 7h8.17l1.313-7H3.102zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm-7 1a1 1 0 1 0 0 2 1 1 0 0 0 0-2zm7 0a1 1 0 1 0 0 2 1 1 0 0 0 0-2z"/>
                    </svg>
                </a>
            {% endif %}
                {% if user.is_authenticated %}
                    {% if user.is_superuser or user.is_staff %}
                        <a class="nav-item nav-link" href="{% url 'admin:index' %}">Panel administracyjny</a>
                    {% endif %}
                    <a class="nav-item nav-link" href="{% url 'users-address_list' %}">
                        <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-journal" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                          <path d="M3 0h10a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2v-1h1v1a1 1 0 0 0 1 1h10a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H3a1 1 0 0 0-1 1v1H1V2a2 2 0 0 1 2-2z"/>
                          <path d="M1 5v-.5a.5.5 0 0 1 1 0V5h.5a.5.5 0 0 1 0 1h-2a.5.5 0 0 1 0-1H1zm0 3v-.5a.5.5 0 0 1 1 0V8h.5a.5.5 0 0 1 0 1h-2a.5.5 0 0 1 0-1H1zm0 3v-.5a.5.5 0 0 1 1 0v.5h.5a.5.5 0 0 1 0 1h-2a.5.5 0 0 1 0-1H1z"/>
                        </svg>
                        Moje konto
                    </a>
                    <a class="nav-item nav-link" href="{% url 'orders-orders' user.email %}">
                        <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-truck" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                          <path fill-rule="evenodd" d="M0 3.5A1.5 1.5 0 0 1 1.5 2h9A1.5 1.5 0 0 1 12 3.5V5h1.02a1.5 1.5 0 0 1 1.17.563l1.481 1.85a1.5 1.5 0 0 1 .329.938V10.5a1.5 1.5 0 0 1-1.5 1.5H14a2 2 0 1 1-4 0H5a2 2 0 1 1-3.998-.085A1.5 1.5 0 0 1 0 10.5v-7zm1.294 7.456A1.999 1.999 0 0 1 4.732 11h5.536a2.01 2.01 0 0 1 .732-.732V3.5a.5.5 0 0 0-.5-.5h-9a.5.5 0 0 0-.5.5v7a.5.5 0 0 0 .294.456zM12 10a2 2 0 0 1 1.732 1h.768a.5.5 0 0 0 .5-.5V8.35a.5.5 0 0 0-.11-.312l-1.48-1.85A.5.5 0 0 0 13.02 6H12v4zm-9 1a1 1 0 1 0 0 2 1 1 0 0 0 0-2zm9 0a1 1 0 1 0 0 2 1 1 0 0 0 0-2z"/>
                        </svg>
                        Zamówienia
                    </a>
                    <a class="nav-item nav-link" href="{% url 'users-logout' %}">Wyloguj się</a>
                {% else %}
                    <a class="nav-item nav-link" href="{% url 'users-login' %}">Logowanie</a>
                    <a class="nav-item nav-link" href="{% url 'users-register' %}">Rejestracja</a>

                {% endif %}
            </div>
          </div>
        </div>
      </nav>
    </header>
    <main role="main" class="container">
      {% if messages %}
          {% for message in messages %}
              <div class="alert alert-{{ message.tags }}">
                {{ message }}
              </div>
          {% endfor %}
      {% endif %}
    {% block content %}{% endblock %}
    </main>

    <footer class="footer">
        <div class="container">
            <span>©Tomasz Wańczyk</span>
        </div>
    </footer>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

restaurants/templates/restaurants/food_detail.html
{% extends 'restaurants/base.html' %}
{% block content %}
    <article class="content-section">
        <div class="container">
            <h3>{{ food_detail.name }}</h3>
            <div class="row justify-content-center">

                <div class="col-">
                    {% for image in food_detail.foodimage_set.all%}
                        <img class="img-fluid img-thumbnail"  src="{{ image.thumbnail.url }}" alt="FoodImage">
                    {% endfor %}
                </div>

                <div class="col align-self-center">
                    Cena: {{ food_detail.price }} zł <br>
                    {{ food_detail.description|linebreaks }}
                </div>

                <div class="col-">
                    {% if food_detail.qr_code %}
                            <div class="scan-qr-container">
                                 <img class="qr-code" src="{{ food_detail.qr_code.url }}" alt="qrcode">
                                <div class="middle">
                                    <button class="read-qr btn btn-success" onclick="alert(value);" value="{{ food_detail.read_qr_code }}">Skanuj</button>
                                </div>
                            </div>
                    {% endif %}
                </div>
            </div>
            <div class="row justify-content-end">
                <a class="btn btn-success mt-2" href="{% url 'orders-add_to_cart' %}?food_id={{ food_detail.id }}">Dodaj do koszyka {{ food_detail.price }} zł</a>
            </div>
        </div>
        <hr>
    <a href="{% url 'restaurants-foods' food_detail.restaurant.slug %}">Powrót</a>
    </article>

{% endblock %}

restaurants/templates/restaurants/index.html
{% extends 'restaurants/base.html' %}
{% block content %}
    <div class="content-section">
    <span>
        <h1 class="display-1 text-center">Witaj na Student zamawia!</h1>
    </span>

        <h1 class="text-center">
            Nasz serwis oferuje wiele potraw oraz dostarcza je na terenie całego Krakowa.
        </h1>
        <h3 class="text-center">Napewno znajdziesz coś dla siebie.</h3>
        <h5 class="text-center">
            <small class="text-muted">Kliknij link poniżej aby skorzystać z naszej oferty</small>
        </h5>
        <h1 class="display-4 text-center">
           <b><a href="{% url 'restaurants-list' %}">Lista restauracji</a></b>
        </h1>
    </div>

{% endblock %}

restaurants/templates/restaurants/restaurant_foods.html
{% extends 'restaurants/base.html' %}
{% block content %}
    <article class="content-section">
    {% if foods %}
        <nav class="navbar navbar-expand-md">Kategorie:
            <a class="nav-item nav-link" href="{% url 'restaurants-foods' view.kwargs.slug %}">
                {% if view.kwargs.category__id == None %}
                    <b>Wszystkie</b>
                {% else %}
                    Wszystkie
                {% endif %}
            </a>
            {% for category in categories %}

                <a class="nav-item nav-link" href="{% url 'restaurants-foods-category' view.kwargs.slug category.id %}">
                    {% if category.id == view.kwargs.category__id %}
                        <b>{{ category }}</b>
                    {% else %}
                        {{ category }}
                    {% endif %}
                </a>
            {% endfor %}
        </nav>
        <hr>
        {% for food in foods %}
            {% if forloop.first %} <!-- display restaurant name only once -->
                <h1>Posiłki restauracji {{ food.restaurant.name }}</h1>
                <span>
                    <h3>Pyszne potrawy dla studentów i nie tylko!</h3>
                    <h4>{{ food.restaurant.city }}, {{ food.restaurant.address }}</h4>
                </span>
            {% endif %}
            <hr>
            <div class="container">
              <h2 class="text-center"><a href="{% url 'food-detail' food.restaurant.slug food.slug %}">{{ food.name }}</a></h2>
                <div class="row justify-content-center">
                    <div class="col-">
                        {% for img in food.foodimage_set.all %}
                            <img class="img-fluid img-thumbnail mb-2 mt-2" src="{{ img.thumbnail.url }}" alt="product thumbnail">
                        {% endfor %}
                    </div>
                    <div class="col-md align-self-center">
                        Kategoria:{% for category in food.category.all %} {{ category }} {% endfor %}<br>
                        {{ food.description|linebreaks }}
                    </div>
                    <div class="col-">
                        {% if food.qr_code %}
                            <div class="scan-qr-container">
                                 <img class="qr-code" src="{{ food.qr_code.url }}" alt="qrcode">
                                <div class="middle">
                                    <button class="read-qr btn btn-success" onclick="alert(value);" value="{{ food.read_qr_code }}">Skanuj</button>
                                </div>
                            </div>
                        {% endif %}
                    </div>
                </div>

                <div class="row justify-content-end">
                    <a class="btn btn-success mt-2" href="{% url 'orders-add_to_cart' %}?food_id={{ food.id }}">Dodaj do koszyka {{ food.price }} zł</a>
                </div>
            </div>
        {% endfor %}
    {% else %}
        <h4 class="text-center">Ta restauracja nie dodała jeszcze nic do swojej oferty</h4>
    {% endif %}
    </article>
{% endblock %} %}

restaurants/templates/restaurants/restaurant_list.html
{% extends 'restaurants/base.html' %}
{% block content %}
    <article class="content-section">
    <h1 class="text-center">Dostępne restauracje</h1>
    {% for restaurant in restaurants %}
        <div class="row align-items-center">
            <div class="col-">
                <a href="{% url 'restaurants-foods' restaurant.slug %}">
                    <img class="rounded-circle img-fluid" src="{{ restaurant.image.url }}">
                </a>
            </div>

            <div class="col">
                <a href="{% url 'restaurants-foods' restaurant.slug %}"><h4>{{ restaurant.name }}</h4></a>
                    <h5>Adres: {{ restaurant.city }}, {{ restaurant.address }} </h5>
            </div>
        </div>
        <hr>
        {% if forloop.last %}
            <a href="{% url 'restaurants-index' %}">Powrót do strony głównej</a>
        {% endif %}
    {% endfor %}
    </article>
{% endblock %} %}